python3 ./fetchinfo.py https://github.com/tomgi/git_stats commits
python3 ./fetchinfo.py https://github.com/arzzen/git-quick-stats commits
python3 ./fetchinfo.py https://github.com/coolstar/electra commits
python3 ./fetchinfo.py https://github.com/Matchstic/ReProvision commits
python3 ./fetchinfo.py https://github.com/Microsoft/MS-DOS commits
python3 ./fetchinfo.py https://github.com/electron/electron commits
python3 ./fetchinfo.py https://github.com/Microsoft/vscode commits
python3 ./fetchinfo.py https://github.com/atom/atom commits
python3 ./fetchinfo.py https://github.com/segmentio/nightmare commits
python3 ./fetchinfo.py https://github.com/highlightjs/highlight.js commits
python3 ./fetchinfo.py https://github.com/jquery/jquery commits
python3 ./fetchinfo.py https://github.com/facebook/react commits
python3 ./fetchinfo.py https://github.com/novus/nvd3 commits
python3 ./fetchinfo.py https://github.com/angular/angular commits
python3 ./fetchinfo.py https://github.com/angular/angular.js commits
python3 ./fetchinfo.py https://github.com/vuejs/vue commits
python3 ./fetchinfo.py https://github.com/flutter/flutter commits
python3 ./fetchinfo.py https://github.com/Bilibili/ijkplayer commits
python3 ./fetchinfo.py https://github.com/SDWebImage/SDWebImage commits
python3 ./fetchinfo.py https://github.com/alibaba/weex commits
python3 ./fetchinfo.py https://github.com/webpack/webpack commits
python3 ./fetchinfo.py https://github.com/rust-lang/rust commits
python3 ./fetchinfo.py https://github.com/parcel-bundler/parcel commits
python3 ./fetchinfo.py https://github.com/JetBrains/kotlin commits
python3 ./fetchinfo.py https://github.com/markedjs/marked commits
python3 ./fetchinfo.py https://github.com/v8/v8 commits
python3 ./fetchinfo.py https://github.com/sveltejs/svelte commits
python3 ./fetchinfo.py https://github.com/nim-lang/Nim commits
python3 ./fetchinfo.py https://github.com/elm/compiler commits
python3 ./fetchinfo.py https://github.com/lebab/lebab commits
